FROM ubuntu:16.04
MAINTAINER jiang_yi_bo@sinzuo.com
RUN apt-get update && apt-get install wget
RUN wget https://github.com/zhaojh329/rttys/files/2471995/rttys-linux-amd64.tar.gz 
RUN tar -zxvf rttys-linux-amd64.tar.gz
RUN . /root/rttys-linux-amd64/rttys